Updating addRecord method signature to match Monolog
signifyd/magento2 pull request #57
Opened 2022-02-09 17:20 UTC by JustinConabreeAbsolunet

Magento 2.4.4 updates the Monolog Logger package to v2.3. The method signature in the new version includes strict typing, causing fatal errors. Have not tested if there are other changes necessary.

```
Fatal error: Declaration of Signifyd\Connect\Logger\Logger::addRecord($level, $message, array $context = []) must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = []): bool in /var/www/html/vendor/signifyd/module-connect/Logger/Logger.php on line 49
```

2022-04-06 14:25 UTC, JeoffScott commented
please merge this to a new release

2022-04-19 19:10 UTC, zeeshan2523806 commented
@JeoffScott @JustinConabreeAbsolunet  @ebanolopes  not sure who is the owner, but can we merge this into release?

2022-05-04 12:41 UTC, JustinConabreeAbsolunet commented
@ebanolopes Any update on this? Current version is not compatible with latest 2.4.4

2022-05-09 10:11 UTC, esprit-dev commented
Hi, the same issue here, please can you give us some updates about 2.4.4 compatibility please ? Many thanks

2022-06-21 16:31 UTC, serzhik approved these changes

2022-06-21 16:48 UTC, justinconabree commented
Note the method signature changes again in monolog/monolog >= 2.7. They've added another parameter for the datetime.

Should update the method signature/usage to match, restrict the version in your composer.json, or find a way around this logger file to avoid future problems (ex virtual type + plugin)

2022-06-21 18:04 UTC, serzhik commented
@JustinConabreeAbsolunet you are right.

Current monolog/monolog use this:
`public function addRecord(int $level, string $message, array $context = [], DateTimeImmutable $datetime = null): bool`

2022-06-21 18:05 UTC, serzhik requested changes
@JustinConabreeAbsolunet you are right.

Current monolog/monolog use this:
`public function addRecord(int $level, string $message, array $context = [], DateTimeImmutable $datetime = null): bool`

2022-07-12 16:56 UTC, valenciaisaza commented
Hi, some update on this PR? we cannot upgrade to Magento 2.4.4 because this error. Thanks

2022-07-12 16:59 UTC, serzhik commented
@valenciaisaza this patch could help:

`Index: Logger/Logger.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Logger/Logger.php b/Logger/Logger.php
--- a/Logger/Logger.php	(revision 6d15a804f22c009a996dc796ddc1fe43a25462de)
+++ b/Logger/Logger.php	(date 1655834194968)
@@ -8,6 +8,7 @@
 namespace Signifyd\Connect\Logger;

 use Signifyd\Connect\Helper\ConfigHelper;
+use Monolog\DateTimeImmutable;

 class Logger extends \Monolog\Logger
 {
@@ -46,7 +47,7 @@
      * @param array $context
      * @return bool
      */
-    public function addRecord($level, $message, array $context = [])
+    public function addRecord(int $level, string $message, array $context = [], DateTimeImmutable $datetime = null): bool
     {
         if (isset($context['entity'])) {
             $log = $this->configHelper->getConfigData('signifyd/logs/log', $context['entity']);
`

2022-08-17 22:43 UTC, lfolco commented
Seriously guys please merge this, 2.4.5 is out already.

2022-08-18 11:11 UTC, ebanolopes commented
Hello. A version compatible with Magento 2.4.4 has been releases to Magento Marketplace at the end of June. However it does not include the specific fix purposed on this discussion. We'll add it to the next version, 5.1.0. Thanks all for the collaboration.

2022-08-18 11:11 UTC, closed without merging

2022-08-23 18:00 UTC, dfelton commented
> Hello. A version compatible with Magento 2.4.4 has been releases to Magento Marketplace at the end of June. However it does not include the specific fix purposed on this discussion. We'll add it to the next version, 5.1.0. Thanks all for the collaboration.

So... why would you close the issue then?